---
galaxy_info:
  role_name: common
  author: thorian93
  description: Common System Management
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - common
