---
- name: "Configure Proxy for systemd."
  block:
    - name: "Ensure systemd configuration directory exists."
      ansible.builtin.file:
        dest: /etc/systemd/system.conf.d
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: "Configure proxy as systemd default."
      ansible.builtin.template:
        dest: /etc/systemd/system.conf.d/99proxy.conf
        src: 99proxy.conf.j2
        mode: 0644
        owner: root
        group: root

  when: ( proxy_server | length ) and ( proxy_port | length )

- name: "Remove proxy from systemd default."
  ansible.builtin.file:
    dest: /etc/systemd/system.conf.d/99proxy.conf
    state: absent
  when: ( not proxy_server | length ) or ( not proxy_port | length )


- name: "Reload systemd configuration."
  ansible.builtin.systemd:
    daemon-reload: true
