---
- name: Create Certificates Folder.
  ansible.builtin.file:
    path: /etc/pki/ca-trust/source/anchors
    state: directory
    owner: root
    group: root
    mode: 0755

- name: Copy the Certificates.
  ansible.builtin.template:
    src: "certificate.pem.j2"
    dest: "/etc/pki/ca-trust/source/anchors/certificate_{{ item.name }}.pem"
    owner: root
    group: root
    mode: 0644
  with_items: "{{ certmanage_certificates }}"
  notify: update trust
