---
galaxy_info:
  author: thorian93
  description: Local Certificate Store Management
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - cert
    - pki
    - ca
    - certificate
    - system
    - encryption

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - Stretch
        - Buster
        - Bullseye
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36
    - name: Ubuntu
      versions:
        - Xenial
        - Bionic
        - Focal
