---
galaxy_info:
  role_name: sudo
  author: thorian93
  description: Sudo Permission Management
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - system
    - sudo
