---
galaxy_info:
  role_name: ntp
  author: thorian93
  description: NTP Network Time Daemon
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - ntp
    - time
    - date
    - system

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - Jessie
        - Stretch
        - Buster
        - Bullseye
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
    - name: SLES
      versions:
        - 11
        - 12
    - name: opensuse
      versions:
        - 15.2
    - name: Ubuntu
      versions:
        - Trusty
        - Xenial
        - Bionic
