---
- name: Converge
  hosts: all

  pre_tasks:

    - name: "Update APT cache."
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'
    - name: "Install prerequisites."
      ansible.builtin.apt:
        name: "{{ item }}"
        state: present
      loop:
        - apt-utils
        - man
      when: ansible_os_family == 'Debian'
    - name: "Create '/usr/share/man/man8/' on Ubuntu."
      ansible.builtin.file:
        path: /usr/share/man/man8/
        state: directory
        mode: "0755"
        owner: root
        group: root
      when: ansible_distribution == 'Ubuntu'

    - name: "Inject file to test Checkmk APT plugin trigger logic."
      block:
        - name: "Create directory."
          ansible.builtin.file:
            path: /var/lib/check_mk_agent/cache/
            state: directory
            recurse: true

        - name: "Create file."
          ansible.builtin.file:
            path: /var/lib/check_mk_agent/cache/plugins_mk_apt.cache
            state: touch

  tasks:

    - name: "Run role."
      ansible.builtin.include_role:
        name: upgrade
