---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: "Test Server is upgraded."
      ansible.builtin.package:
        name: "*"
        state: "latest"
      register: server_upgrade_status

    - debug: var=server_upgrade_status

    - name: "Verify Server is upgraded."
      ansible.builtin.assert:
        that: not server_upgrade_status.changed and not server_upgrade_status.failed
