---
galaxy_info:
  role_name: journald
  author: thorian93
  description: Journald logging daemon
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - system
    - logging
    - logs
    - journald
    - journalctl
