---
galaxy_info:
  role_name: proxy
  author: thorian93
  description: Local Proxy Management
  license: "license (MIT)"

  issue_tracker_url: https://github.com/thorian93/main/issues

  min_ansible_version: "2.9"

  galaxy_tags:
    - linux
    - server
    - common
    - proxy
    - web

  platforms:
    - name: EL
      versions:
        - all
    - name: Debian
      versions:
        - Stretch
        - Buster
        - Bullseye
    - name: Fedora
      versions:
        - 30
        - 31
        - 32
        - 33
        - 34
        - 35
        - 36
    - name: opensuse
      versions:
        - 15.2
        - 42.2
    - name: Ubuntu
      versions:
        - Xenial
        - Bionic
        - Focal

dependencies:
  - role: thorian93.main.webserver
