---
- name: "Restart SSH Service"
  listen: restart ssh
  ansible.builtin.service:
    name: sshd
    state: restarted

- name: "Reload SSH Service"
  listen: reload ssh
  ansible.builtin.service:
    name: sshd
    state: reloaded
