---
- name: Converge
  hosts: all

  pre_tasks:

    - name: "Update APT Cache."
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 600
      when: ansible_os_family == 'Debian'

    - name: "Ensure SSHD is installed."
      ansible.builtin.package:
        name: openssh-server
        state: present

    - name: "Ensure SSHD is running."
      ansible.builtin.service:
        name: sshd
        state: started

  tasks:

    - name: "Run role."
      ansible.builtin.include_role:
        name: ssh
