---
- name: Converge
  hosts: all

  pre_tasks:

  - name: "Ensure SSHD is installed."
    ansible.builtin.package:
      name: openssh-server
      state: present

  - name: "Ensure SSHD is running."
    ansible.builtin.service:
      name: sshd
      state: started

  tasks:

    - name: "Run role."
      ansible.builtin.include_role:
        name: ssh
