---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Populate service facts.
      ansible.builtin.service_facts:

    - name: "Test SSH Service is running."
      ansible.builtin.assert:
        that: "'sshd.service' in ansible_facts.services"

    - name: "Test that SSH is listening on Port {{ ssh_port }}."
      ansible.builtin.wait_for:
        port: "{{ ssh_port }}"
        connect_timeout: 30
      register: ssh_port_state

    - name: "Verify that SSH Service is listening on port {{ ssh_port }}."
      ansible.builtin.assert:
        that: "(ssh_port_state.port == ssh_port) and (ssh_port_state.state == 'started')"

    - name: "Verify SSHD Port."
      lineinfile:
        name: /etc/ssh/sshd_config
        line: "Port {{ ssh_port }}"
        state: present
      check_mode: true
      register: ssh_conf
      failed_when: (ssh_conf is changed) or (ssh_conf is failed)

# {% if ssh_port is defined and ssh_port | length %}
# Port {{ ssh_port }}
# {% else %}
# #Port 22
# {% endif %}
# {% if ssh_protocol is defined and ssh_protocol | length %}
# Protocol {{ ssh_protocol }}
# {% else %}
# #Protocol 2
# {% endif %}
# {% if ssh_address_family is defined and ssh_address_family | length %}
# AddressFamily {{ ssh_address_family }}
# {% else %}
# #AddressFamily any
# {% endif %}
# {% if ssh_listen_address is defined and ssh_listen_address | length %}
# ListenAddress {{ ssh_listen_address }}
# {% else %}
# #ListenAddress 0.0.0.0
# #ListenAddress ::
# {% endif %}

# # Ciphers and keying
# #RekeyLimit default none

# # Ciphers
# {% if ssh_ciphers is defined and ssh_ciphers | length %}
# Ciphers {{ ssh_ciphers }}
# {% endif %}
# {% if ssh_enabled_ciphers is defined and ssh_enabled_ciphers | length %}
# Ciphers +{{ ssh_enabled_ciphers }}
# {% endif %}
# {% if ssh_disabled_ciphers is defined and ssh_disabled_ciphers | length %}
# {% if
# (ansible_distribution == 'Debian' and ansible_distribution_version is version('10', '>='))
# or (ansible_distribution == 'Ubuntu' and ansible_distribution_version is version('18', '>='))
# or (ansible_distribution == 'CentOS' and ansible_distribution_version is version('8', '>='))
# %}
# Ciphers -{{ ssh_disabled_ciphers }}
# {% endif %}
# {% endif %}

# # Logging
# #SyslogFacility AUTH
# #LogLevel INFO

# # Authentication:

# #LoginGraceTime 2m
# {% if ssh_permit_root_login is defined and ssh_permit_root_login | bool %}
# PermitRootLogin yes
# {% elif ssh_permit_root_login | string | length %}
# PermitRootLogin {{ ssh_permit_root_login }}
# {% else %}
# #PermitRootLogin prohibit-password
# {% endif %}
# {% if ssh_strict_mode is defined and ssh_strict_mode | bool %}
# StrictModes yes
# {% else %}
# #StrictModes yes
# {% endif %}
# #MaxAuthTries 6
# #MaxSessions 10

# #PubkeyAuthentication yes

# # To disable tunneled clear text passwords, change to no here!
# {% if ssh_permit_password_authentication is defined and ssh_permit_password_authentication | bool %}
# PasswordAuthentication {{ ssh_permit_password_authentication }}
# {% else %}
# #PasswordAuthentication yes
# {% endif %}
# {% if ssh_permit_empty_passwords is defined and ssh_permit_empty_passwords | bool %}
# PermitEmptyPasswords {{ ssh_permit_empty_passwords }}
# {% else %}
# #PermitEmptyPasswords no
# {% endif %}

# # Change to yes to enable challenge-response passwords (beware issues with
# # some PAM modules and threads)
# {% if ssh_challenge_response_auth is defined and ssh_challenge_response_auth | bool %}
# ChallengeResponseAuthentication {{ ssh_challenge_response_auth }}
# {% else %}
# ChallengeResponseAuthentication no
# {% endif %}

# # GSSAPI options
# {% if ssh_gss_api_authentication is defined and ssh_gss_api_authentication | bool %}
# GSSAPIAuthentication {{ ssh_gss_api_authentication }}
# {% else %}
# #GSSAPIAuthentication no
# {% endif %}
# #GSSAPICleanupCredentials yes
# #GSSAPIStrictAcceptorCheck yes
# #GSSAPIKeyExchange no

# #AllowAgentForwarding yes
# #AllowTcpForwarding yes
# #GatewayPorts no
# {% if ssh_allow_x11_forwarding is defined and ssh_allow_x11_forwarding | bool %}
# X11Forwarding {{ ssh_allow_x11_forwarding }}
# {% else %}
# X11Forwarding no
# {% endif %}
# #X11DisplayOffset 10
# #X11UseLocalhost yes
# #PermitTTY yes
# {% if ssh_print_motd is defined and ssh_print_motd | bool %}
# PrintMotd {{ ssh_print_motd }}
# {% else %}
# PrintMotd no
# {% endif %}

# {% if ssh_print_banner is defined and ssh_print_banner | bool %}
# {% if ssh_banner_file is defined and ssh_banner_file | length %}
# Banner {{ ssh_banner_file }}
# {% endif %}
# {% else %}
# # no default banner path
# #Banner none
# {% endif %}

# {% if ssh_usedns is defined and ssh_usedns | bool %}
# UseDNS {{ ssh_usedns }}
# {% else %}
# UseDNS no
# {% endif %}
# {% if ssh_allowed_users is defined and ssh_allowed_users | length %}
# AllowUsers {{ ssh_allowed_users }}
# {% endif %}
# {% if ssh_allowed_groups is defined and ssh_allowed_groups | length %}
# AllowGroups {{ ssh_allowed_groups }}
# {% endif %}


# {% if ssh_vault_trusted_ca_enable is defined and ssh_vault_trusted_ca_enable | bool %}
# # Vault CA Keys
# TrustedUserCAKeys /etc/ssh/{{ ssh_vault_ca_cert | default('trusted-user-ca-keys.pem')}}
# {% endif %}
