---
- name: Verify
  hosts: all
  gather_facts: false
  tasks:

    - name: Populate service facts.
      ansible.builtin.service_facts:

    - name: "Test SSH Service is running."
      ansible.builtin.assert:
        that: "'sshd.service' in ansible_facts.services"

    - name: "Test that SSH is listening on Port {{ ssh_port }}."
      ansible.builtin.wait_for:
        port: "{{ ssh_port }}"
        connect_timeout: 30
      register: ssh_port_state

    - name: "Verify that SSH Service is listening on port {{ ssh_port }}."
      ansible.builtin.assert:
        that: "(ssh_port_state.port == ssh_port) and (ssh_port_state.state == 'started')"

    - name: "Verify SSHD Port."
      lineinfile:
        name: /etc/ssh/sshd_config
        line: "Port {{ ssh_port }}"
        state: present
      check_mode: true
      register: ssh_conf
      failed_when: (ssh_conf is changed) or (ssh_conf is failed)
