---
webserver_stable_os:
  - CentOS 7
  - CentOS 8
  - Debian 9
  - Debian 10
  - Debian 11
  - Debian 12
  - Fedora 37
  - Fedora 38
  - Fedora 39
  - Fedora 40
  - openSUSE Leap 15
  - openSUSE Leap 42
  - Rocky 9
  - Ubuntu 16
  - Ubuntu 18
  - Ubuntu 20
  - Ubuntu 22
  - Ubuntu 24

webserver_name: []
webserver_user: []
webserver_conf_file: []
