---
common_apps_derivate:
  - apt-transport-https
  - aptitude
  - bash-completion
  - bind9-dnsutils
  - debian-goodies
  - iftop
  - inotify-tools
  - iptstate
  - lnav
  - lsb-release
  - mailutils
  - net-tools
  - nmon
  - p7zip
  - tig
  - tuptime
  - unar
  - unison
  - whois
  - xz-utils

common_timezone_package: tzdata
common_vimrc_path: /etc/vim/vimrc
common_admin_group: sudo
