---
- hosts: my_test_host
  become: true
  roles:
    - certmanage

- hosts: my_test_host
  name: "Common."
  become: true
  roles:
    - common

- hosts: my_test_host
  become: true
  roles:
    - journald

- hosts: my_test_host
  become: true
  roles:
    - logrotate

- hosts: my_test_host
  become: true
  roles:
    - ntp

- hosts: my_test_host
  name: "Proxy."
  become: true
  roles:
    - proxy

- hosts: my_test_host
  become: true
  roles:
    - ssh

- hosts: my_test_host
  become: true
  roles:
    - sudo

- hosts: my_test_host
  become: true
  roles:
    - upgrade
