---
name: Release Collection

on: # yamllint disable-line rule:truthy
  workflow_dispatch:

env:
  NAMESPACE: thorian93
  COLLECTION_NAME: main
  FILES: "CHANGELOG.rst LICENSE README.md ansible.cfg galaxy.yml"
  DIRS: "changelogs meta playbooks roles"

jobs:
  release:
    runs-on: ubuntu-latest

    steps:

      #
      # Prepare the environment.
      #

      - name: Checkout code
        uses: actions/checkout@v4

      - name: Get current version
        id: current_version
        run: echo "version=$(grep 'version:' galaxy.yml | cut -d ' ' -f 2)" >> $GITHUB_OUTPUT

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      #
      # First stage: Build and install collection to generate docs and changelogs.
      #

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
        env:
          files: ${{env.FILES}}
          directories: ${{env.DIRS}}

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force

      - name: Install Ansible Collection
        run: ansible-galaxy collection install --no-deps ./${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${{ steps.current_version.outputs.version }}.tar.gz

      - name: Compile Collection Changelog
        run: antsibull-changelog release

      - name: Create Pull Request for docs and changelog against devel branch
        uses: peter-evans/create-pull-request@v6
        with:
          commit-message: Update Changelogs
          signoff: false
          branch: changelogs-update-${{ steps.current_version.outputs.version }}
          base: devel
          delete-branch: true
          title: '[Auto] Update changelogs for ${{ steps.current_version.outputs.version }}'
          body: |
            Changelogs updated during *${{ steps.current_version.outputs.version }}* release.
          assignees: thorian93
          reviewers: thorian93
          draft: false

      #
      # Second stage: Build the final version of the collection and release it.
      #

      - name: Copy Files and Directories to Source
        run: |
          mkdir -p build/src
          cp $files build/src
          cp -rf $directories build/src
          rm -rf build/src/roles/*/molecule
        env:
          files: ${{env.FILES}}
          directories: ${{env.DIRS}}

      - name: Build Ansible Collection
        run: ansible-galaxy collection build build/src --force

      - name: Create Release and upload Assets
        id: create-release
        uses: softprops/action-gh-release@v2
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          draft: false
          prerelease: false
          name: v${{ steps.current_version.outputs.version }}
          tag_name: v${{ steps.current_version.outputs.version }}
          files: ${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${{ steps.current_version.outputs.version }}.tar.gz
          body: |
            # Ansible Collection: ${{env.NAMESPACE}}.${{env.COLLECTION_NAME}}

            For information about this collection and how to install it, refer to the [README](https://github.com/thorian93/main/blob/main/README.md).

            For a detailed changelog, refer to the [CHANGELOG](https://github.com/thorian93/main/blob/main/CHANGELOG.rst).

            This collection can be found in the [Galaxy](https://galaxy.ansible.com/ui/repo/published/thorian93/main/) as well!

      - name: Publish Ansible Collection to the Galaxy
        run: ansible-galaxy collection publish ${{env.NAMESPACE}}-${{env.COLLECTION_NAME}}-${{ steps.current_version.outputs.version }}.tar.gz --api-key ${{ secrets.GALAXY_API_KEY }}
